# Generated by Django 3.2.6 on 2021-09-16 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('balance', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('transaction_time', models.DateTimeField()),
                ('category', models.IntegerField(choices=[(1, 'Cash'), (2, 'Salary'), (3, 'Healthcare'), (5, 'Travel'), (6, 'Food'), (7, 'Other')])),
                ('amount', models.IntegerField(default=0)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.cashaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
