# Generated by Django 3.2.7 on 2021-09-29 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splittransaction',
            name='users_in_split',
        ),
        migrations.AddField(
            model_name='splittransaction',
            name='friends_paid',
            field=models.ManyToManyField(related_name='paid_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='splittransaction',
            name='all_friends_involved',
            field=models.ManyToManyField(related_name='involved_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
