# Generated by Django 3.2.6 on 2021-09-21 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='schedule_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.IntegerField(choices=[(0, 'Income'), (1, 'Drink'), (2, 'Fuel'), (3, 'Healthcare'), (4, 'Travel'), (5, 'Food'), (6, 'Grocery'), (7, 'Other')]),
        ),
        migrations.AlterUniqueTogether(
            name='cashaccount',
            unique_together={('user', 'title')},
        ),
    ]
