# Generated by Django 3.2.7 on 2021-09-27 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.IntegerField(choices=[(0, 'Income'), (1, 'Drink'), (2, 'Fuel'), (3, 'Healthcare'), (4, 'Travel'), (5, 'Food'), (6, 'Grocery'), (7, 'Other')])),
                ('total_amount', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('payed_users', models.ManyToManyField(related_name='payedUsers', to=settings.AUTH_USER_MODEL)),
                ('users_in_split', models.ManyToManyField(related_name='split_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
