# Generated by Django 3.2.7 on 2021-09-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='split_expense',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.splittransaction'),
        ),
    ]
