# Generated by Django 3.2.6 on 2021-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_budget_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.TextField(choices=[(1, 'Cash'), (2, 'Salary'), (3, 'Healthcare'), (5, 'Travel'), (6, 'Food'), (7, 'Other')]),
        ),
    ]
