# Generated by Django 3.2.7 on 2021-09-21 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_auto_20210921_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='schedule_time',
        ),
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('scheduled_time', models.DateTimeField()),
                ('category', models.IntegerField(choices=[(0, 'Income'), (1, 'Drink'), (2, 'Fuel'), (3, 'Healthcare'), (4, 'Travel'), (5, 'Food'), (6, 'Grocery'), (7, 'Other')])),
                ('amount', models.IntegerField(default=0)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.cashaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
