# Generated by Django 3.2.7 on 2021-09-27 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_splittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splittransaction',
            name='payed_users',
            field=models.ManyToManyField(blank=True, related_name='payedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
