# Generated by Django 3.2.6 on 2021-09-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Salary'), (3, 'Healthcare'), (5, 'Travel'), (6, 'Food'), (7, 'Other')]),
        ),
    ]
