# Generated by Django 3.2.7 on 2021-09-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_split_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splittransaction',
            name='friends_paid',
        ),
    ]
