# Generated by Django 3.2.7 on 2021-09-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendrequest_request_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('user', 'receiver')},
        ),
    ]
