# Generated by Django 3.2.8 on 2021-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailauthenticateduser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailauthenticateduser',
            name='display_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
