# Generated by Django 3.2.9 on 2021-11-18 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
