name: CI
on:
  [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install pipenv
          pipenv install

      - name: Tests with pytests
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TWILIO_PHN_NUM: ${{ secrets.TWILIO_PHN_NUM }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          DJANGO_SETTINGS_MODULE: budget_tracker.settings
        run: |
          pipenv run pytest
          
